; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ 3.3.6
    adafruit/Adafruit_VL53L0X @ 1.2.4
