; PlatformIO Project Configuration File

[env:esp32dev]
; --- Hardware Architecture -- ;
platform = espressif32 ; Microchip Family
board = esp32dev ; Specific Model
framework = arduino ; Core Programming Language/API

; --- Serial Monitor -- ;
monitor_speed = 115200 ; Prevents gibberish

; --- Dependancy Management --- ;
lib_deps =
    ; Asyncronous Web Server: Handles WiFi clients simultaneously
    mathieucarbou/ESPAsyncWebServer @ 3.3.6
    
    ; Time-of-Flight Laser Sensors: I2C driver for the VL53L0X modules
    adafruit/Adafruit_VL53L0X @ 1.2.4
